version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    # Ne pas forcer user si tu utilises laraveluser dans Dockerfile
    volumes:
      - .:/var/www:cached
      - vendor:/var/www/vendor
      - storage:/var/www/storage
      - node_modules:/var/www/node_modules
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network
    entrypoint: ["/var/www/docker-entrypoint.sh"]
    ports:
      - 9000:9000
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network

  web:
    image: nginx:1.29-alpine
    container_name: nginx-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:ro
      - storage:/var/www/storage:ro
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
  vendor:
  storage:
  node_modules:

networks:
  app-network:
    driver: bridge
