<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('region', function (Blueprint $table) {
            $table->id();
            $table->string("region");
            $table->unsignedBigInteger('cityId');
            $table->foreign('cityId')->references('id')->on('city')->onDelete('cascade');
        });

        DB::table('region')->insert([
            ['id'=>1, 'region'=>'Ariana City', 'cityId'=>2],
            ['id'=>2, 'region'=>'Ettadhamen', 'cityId'=>2],
            ['id'=>3, 'region'=>'Kalâat Andalous', 'cityId'=>2],
            ['id'=>4, 'region'=>'La Soukra', 'cityId'=>2],
            ['id'=>5, 'region'=>'Mnihla', 'cityId'=>2],
            ['id'=>6, 'region'=>'Raoued', 'cityId'=>2],
            ['id'=>7, 'region'=>'Sidi Thabet', 'cityId'=>2],
            ['id'=>8, 'region'=>'Amdoun', 'cityId'=>8],
            ['id'=>9, 'region'=>'Béja Nord', 'cityId'=>8],
            ['id'=>10, 'region'=>'Béja Sud', 'cityId'=>8],
            ['id'=>11, 'region'=>'Goubellat', 'cityId'=>8],
            ['id'=>12, 'region'=>'Medjez El Bab', 'cityId'=>8],
            ['id'=>13, 'region'=>'Nefza', 'cityId'=>8],
            ['id'=>14, 'region'=>'Teboursouk', 'cityId'=>8],
            ['id'=>15, 'region'=>'Testour', 'cityId'=>8],
            ['id'=>16, 'region'=>'Thibar', 'cityId'=>8],
            ['id'=>17, 'region'=>'Ben Arous', 'cityId'=>3],
            ['id'=>18, 'region'=>'Boumhel', 'cityId'=>3],
            ['id'=>19, 'region'=>'El Mourouj', 'cityId'=>3],
            ['id'=>20, 'region'=>'Ezzahra', 'cityId'=>3],
            ['id'=>21, 'region'=>'Fouchana', 'cityId'=>3],
            ['id'=>22, 'region'=>'Hammam Chott', 'cityId'=>3],
            ['id'=>23, 'region'=>'Hammam Lif', 'cityId'=>3],
            ['id'=>24, 'region'=>'Mhamdia', 'cityId'=>3],
            ['id'=>25, 'region'=>'Medina Jedida', 'cityId'=>3],
            ['id'=>26, 'region'=>'Megrine', 'cityId'=>3],
            ['id'=>27, 'region'=>'Mornag', 'cityId'=>3],
            ['id'=>28, 'region'=>'Rades', 'cityId'=>3],
            ['id'=>29, 'region'=>'Bizerte Nord', 'cityId'=>7],
            ['id'=>30, 'region'=>'Bizerte Sud', 'cityId'=>7],
            ['id'=>31, 'region'=>'Djoumime', 'cityId'=>7],
            ['id'=>32, 'region'=>'El Alia', 'cityId'=>7],
            ['id'=>33, 'region'=>'Ghar El Melh', 'cityId'=>7],
            ['id'=>34, 'region'=>'Ghezala', 'cityId'=>7],
            ['id'=>35, 'region'=>'Mateur', 'cityId'=>7],
            ['id'=>36, 'region'=>'Menzel Bourguiba', 'cityId'=>7],
            ['id'=>37, 'region'=>'Menzel Jemil', 'cityId'=>7],
            ['id'=>38, 'region'=>'Ras Jebel', 'cityId'=>7],
            ['id'=>39, 'region'=>'Sejenane', 'cityId'=>7],
            ['id'=>40, 'region'=>'Tinja', 'cityId'=>7],
            ['id'=>41, 'region'=>'Utique', 'cityId'=>7],
            ['id'=>42, 'region'=>'Zarzouna', 'cityId'=>7],
            ['id'=>43, 'region'=>'Gabès Médina', 'cityId'=>19],
            ['id'=>44, 'region'=>'Gabès Ouest', 'cityId'=>19],
            ['id'=>45, 'region'=>'Gabès Sud', 'cityId'=>19],
            ['id'=>46, 'region'=>'Ghannouch', 'cityId'=>19],
            ['id'=>47, 'region'=>'El Hamma', 'cityId'=>19],
            ['id'=>48, 'region'=>'Mareth', 'cityId'=>19],
            ['id'=>49, 'region'=>'Matmata Ancienne', 'cityId'=>19],
            ['id'=>50, 'region'=>'Matmata Nouvelle', 'cityId'=>19],
            ['id'=>51, 'region'=>'Menzel El Habib', 'cityId'=>19],
            ['id'=>52, 'region'=>'Métouia', 'cityId'=>19],
            ['id'=>53, 'region'=>'Belkhir', 'cityId'=>22],
            ['id'=>54, 'region'=>'Gafsa Nord', 'cityId'=>22],
            ['id'=>55, 'region'=>'Gafsa Sud', 'cityId'=>22],
            ['id'=>56, 'region'=>'El Guettar', 'cityId'=>22],
            ['id'=>57, 'region'=>'El Ksar', 'cityId'=>22],
            ['id'=>58, 'region'=>'Mdhila', 'cityId'=>22],
            ['id'=>59, 'region'=>'Metlaoui', 'cityId'=>22],
            ['id'=>60, 'region'=>'Oum El Araies', 'cityId'=>22],
            ['id'=>61, 'region'=>'Redeyef', 'cityId'=>22],
            ['id'=>62, 'region'=>'Sned', 'cityId'=>22],
            ['id'=>63, 'region'=>'Sidi Aïch', 'cityId'=>22],
            ['id'=>64, 'region'=>'Ain Draham', 'cityId'=>9],
            ['id'=>65, 'region'=>'Balta – Bou Salem', 'cityId'=>9],
            ['id'=>66, 'region'=>'Bou Salem', 'cityId'=>9],
            ['id'=>67, 'region'=>'Fernana', 'cityId'=>9],
            ['id'=>68, 'region'=>'Ghardimaou', 'cityId'=>9],
            ['id'=>69, 'region'=>'Jendouba', 'cityId'=>9],
            ['id'=>70, 'region'=>'Jendouba Nord', 'cityId'=>9],
            ['id'=>71, 'region'=>'Oued Meliz', 'cityId'=>9],
            ['id'=>72, 'region'=>'Tabarka', 'cityId'=>9],
            ['id'=>73, 'region'=>'Bouhajla', 'cityId'=>15],
            ['id'=>74, 'region'=>'Chebika', 'cityId'=>15],
            ['id'=>75, 'region'=>'Echrarda', 'cityId'=>15],
            ['id'=>76, 'region'=>'El Alâa', 'cityId'=>15],
            ['id'=>77, 'region'=>'El Ouslatia', 'cityId'=>15],
            ['id'=>78, 'region'=>'Haffouz', 'cityId'=>15],
            ['id'=>79, 'region'=>'Hajeb El Ayoun', 'cityId'=>15],
            ['id'=>80, 'region'=>'Kairouan Nord', 'cityId'=>15],
            ['id'=>81, 'region'=>'Kairouan Sud', 'cityId'=>15],
            ['id'=>82, 'region'=>'Nasrallah', 'cityId'=>15],
            ['id'=>83, 'region'=>'Sbikha', 'cityId'=>15],
            ['id'=>84, 'region'=>'Djedeliane', 'cityId'=>16],
            ['id'=>85, 'region'=>'El Ayoun', 'cityId'=>16],
            ['id'=>86, 'region'=>'Ezzouhour', 'cityId'=>16],
            ['id'=>87, 'region'=>'Fériana', 'cityId'=>16],
            ['id'=>88, 'region'=>'Foussana', 'cityId'=>16],
            ['id'=>89, 'region'=>'Hassi Ferid', 'cityId'=>16],
            ['id'=>90, 'region'=>'Hidra', 'cityId'=>16],
            ['id'=>91, 'region'=>'Kasserine Nord', 'cityId'=>16],
            ['id'=>92, 'region'=>'Kasserine Sud', 'cityId'=>16],
            ['id'=>93, 'region'=>'Majel Bel Abbès', 'cityId'=>16],
            ['id'=>94, 'region'=>'Sbeïtla', 'cityId'=>16],
            ['id'=>95, 'region'=>'Sbiba', 'cityId'=>16],
            ['id'=>96, 'region'=>'Thala', 'cityId'=>16],
            ['id'=>97, 'region'=>'Douz Nord', 'cityId'=>24],
            ['id'=>98, 'region'=>'Douz Sud', 'cityId'=>24],
            ['id'=>99, 'region'=>'Faouar', 'cityId'=>24],
            ['id'=>100, 'region'=>'Kébili Nord', 'cityId'=>24],
            ['id'=>101, 'region'=>'Kébili Sud', 'cityId'=>24],
            ['id'=>102, 'region'=>'Souk Lahad', 'cityId'=>24],
            ['id'=>103, 'region'=>'Dahmani', 'cityId'=>10],
            ['id'=>104, 'region'=>'Es Sers', 'cityId'=>10],
            ['id'=>105, 'region'=>'Jerissa', 'cityId'=>10],
            ['id'=>106, 'region'=>'Kalâat Khasba', 'cityId'=>10],
            ['id'=>107, 'region'=>'Kalâat Snen', 'cityId'=>10],
            ['id'=>108, 'region'=>'Kef Est', 'cityId'=>10],
            ['id'=>109, 'region'=>'Kef Ouest', 'cityId'=>10],
            ['id'=>110, 'region'=>'Ksour', 'cityId'=>10],
            ['id'=>111, 'region'=>'Nebeur', 'cityId'=>10],
            ['id'=>112, 'region'=>'Sakiet Sidi Youssef', 'cityId'=>10],
            ['id'=>113, 'region'=>'Tajerouine', 'cityId'=>10],
            ['id'=>114, 'region'=>'Bou Merdes', 'cityId'=>14],
            ['id'=>115, 'region'=>'Chebba', 'cityId'=>14],
            ['id'=>116, 'region'=>'Chorbane', 'cityId'=>14],
            ['id'=>117, 'region'=>'El Djem', 'cityId'=>14],
            ['id'=>118, 'region'=>'Hbira', 'cityId'=>14],
            ['id'=>119, 'region'=>'Ksour Essef', 'cityId'=>14],
            ['id'=>120, 'region'=>'Mahdia', 'cityId'=>14],
            ['id'=>121, 'region'=>'Melloulèche', 'cityId'=>14],
            ['id'=>122, 'region'=>'Ouled Chamekh', 'cityId'=>14],
            ['id'=>123, 'region'=>'Sidi Alouane', 'cityId'=>14],
            ['id'=>124, 'region'=>'Essouassi', 'cityId'=>14],
            ['id'=>125, 'region'=>'Ben Gardane', 'cityId'=>20],
            ['id'=>126, 'region'=>'Beni Khedech', 'cityId'=>20],
            ['id'=>127, 'region'=>'Djerba - Ajim', 'cityId'=>20],
            ['id'=>128, 'region'=>'Djerba - Houmt Souk', 'cityId'=>20],
            ['id'=>129, 'region'=>'Djerba - Midoun', 'cityId'=>20],
            ['id'=>130, 'region'=>'Médenine Nord', 'cityId'=>20],
            ['id'=>131, 'region'=>'Médenine Sud', 'cityId'=>20],
            ['id'=>132, 'region'=>'Sidi Makhlouf', 'cityId'=>20],
            ['id'=>133, 'region'=>'Zarzis', 'cityId'=>20],
            ['id'=>134, 'region'=>'Bekalta', 'cityId'=>13],
            ['id'=>135, 'region'=>'Bembla', 'cityId'=>13],
            ['id'=>136, 'region'=>'Béni Hassen', 'cityId'=>13],
            ['id'=>137, 'region'=>'Jemmal', 'cityId'=>13],
            ['id'=>138, 'region'=>'Ksar Hellal', 'cityId'=>13],
            ['id'=>139, 'region'=>'Ksibet El-Médiouni', 'cityId'=>13],
            ['id'=>140, 'region'=>'Moknine', 'cityId'=>13],
            ['id'=>141, 'region'=>'Monastir', 'cityId'=>13],
            ['id'=>142, 'region'=>'Ouerdanine', 'cityId'=>13],
            ['id'=>143, 'region'=>'Sahline', 'cityId'=>13],
            ['id'=>144, 'region'=>'Sayada–Lamta–Bou Hajar', 'cityId'=>13],
            ['id'=>145, 'region'=>'Téboulba', 'cityId'=>13],
            ['id'=>146, 'region'=>'Zéramdine', 'cityId'=>13],
            ['id'=>147, 'region'=>'Béni Khalled', 'cityId'=>5],
            ['id'=>148, 'region'=>'Béni Khiar', 'cityId'=>5],
            ['id'=>149, 'region'=>'Bou Argoub', 'cityId'=>5],
            ['id'=>150, 'region'=>'Dar Châabane El Fehri', 'cityId'=>5],
            ['id'=>151, 'region'=>'El Mida', 'cityId'=>5],
            ['id'=>152, 'region'=>'Grombalia', 'cityId'=>5],
            ['id'=>153, 'region'=>'Hammam El Guezaz', 'cityId'=>5],
            ['id'=>154, 'region'=>'Hammamet', 'cityId'=>5],
            ['id'=>155, 'region'=>'Kélibia', 'cityId'=>5],
            ['id'=>156, 'region'=>'Korba', 'cityId'=>5],
            ['id'=>157, 'region'=>'Menzel Bouzelfa', 'cityId'=>5],
            ['id'=>158, 'region'=>'Menzel Temime', 'cityId'=>5],
            ['id'=>159, 'region'=>'Nabeul', 'cityId'=>5],
            ['id'=>160, 'region'=>'Soliman', 'cityId'=>5],
            ['id'=>161, 'region'=>'Takelsa', 'cityId'=>5],
            ['id'=>162, 'region'=>'Agareb', 'cityId'=>18],
            ['id'=>163, 'region'=>'Bir Ali Ben Khelifa', 'cityId'=>18],
            ['id'=>164, 'region'=>'El Amra', 'cityId'=>18],
            ['id'=>165, 'region'=>'El Hencha', 'cityId'=>18],
            ['id'=>166, 'region'=>'Ghraiba', 'cityId'=>18],
            ['id'=>167, 'region'=>'Jebeniana', 'cityId'=>18],
            ['id'=>168, 'region'=>'Kerkennah', 'cityId'=>18],
            ['id'=>169, 'region'=>'Mahres', 'cityId'=>18],
            ['id'=>170, 'region'=>'Menzel Chaker', 'cityId'=>18],
            ['id'=>171, 'region'=>'Sakiet Eddaïer', 'cityId'=>18],
            ['id'=>172, 'region'=>'Sakiet Ezzit', 'cityId'=>18],
            ['id'=>173, 'region'=>'Sfax Ouest', 'cityId'=>18],
            ['id'=>174, 'region'=>'Sfax Sud', 'cityId'=>18],
            ['id'=>175, 'region'=>'Sfax City', 'cityId'=>18],
            ['id'=>176, 'region'=>'Skhira', 'cityId'=>18],
            ['id'=>177, 'region'=>'Tina', 'cityId'=>18],
            ['id'=>178, 'region'=>'Bir El Hafey', 'cityId'=>17],
            ['id'=>179, 'region'=>'Cebbala Ouled Asker', 'cityId'=>17],
            ['id'=>180, 'region'=>'Jilma', 'cityId'=>17],
            ['id'=>181, 'region'=>'Meknassy', 'cityId'=>17],
            ['id'=>182, 'region'=>'Menzel Bouzaiane', 'cityId'=>17],
            ['id'=>183, 'region'=>'Mezzouna', 'cityId'=>17],
            ['id'=>184, 'region'=>'Ouled Haffouz', 'cityId'=>17],
            ['id'=>185, 'region'=>'Regueb', 'cityId'=>17],
            ['id'=>186, 'region'=>'Sidi Ali Ben Aoûn', 'cityId'=>17],
            ['id'=>187, 'region'=>'Sidi Bouzid Est', 'cityId'=>17],
            ['id'=>188, 'region'=>'Sidi Bouzid Ouest', 'cityId'=>17],
            ['id'=>189, 'region'=>'Souk Jedid', 'cityId'=>17],
            ['id'=>190, 'region'=>'Bargou', 'cityId'=>11],
            ['id'=>191, 'region'=>'Bou Arada', 'cityId'=>11],
            ['id'=>192, 'region'=>'Bourouis', 'cityId'=>11],
            ['id'=>193, 'region'=>'El Aroussa', 'cityId'=>11],
            ['id'=>194, 'region'=>'El Krib', 'cityId'=>11],
            ['id'=>195, 'region'=>'Gaâfour', 'cityId'=>11],
            ['id'=>196, 'region'=>'Kesra', 'cityId'=>11],
            ['id'=>197, 'region'=>'Makthar', 'cityId'=>11],
            ['id'=>198, 'region'=>'Rouhia', 'cityId'=>11],
            ['id'=>199, 'region'=>'Siliana Nord', 'cityId'=>11],
            ['id'=>200, 'region'=>'Siliana Sud', 'cityId'=>11],
            ['id'=>201, 'region'=>'Akouda', 'cityId'=>12],
            ['id'=>202, 'region'=>'Bouficha', 'cityId'=>12],
            ['id'=>203, 'region'=>'Enfidha', 'cityId'=>12],
            ['id'=>204, 'region'=>'Hammam Sousse', 'cityId'=>12],
            ['id'=>205, 'region'=>'Hergla', 'cityId'=>12],
            ['id'=>206, 'region'=>'Kalâa Kebira', 'cityId'=>12],
            ['id'=>207, 'region'=>'Kalâa Sghira', 'cityId'=>12],
            ['id'=>208, 'region'=>'Kondar', 'cityId'=>12],
            ['id'=>209, 'region'=>'Msaken', 'cityId'=>12],
            ['id'=>210, 'region'=>'Sidi Bou Ali', 'cityId'=>12],
            ['id'=>211, 'region'=>'Sidi El Héni', 'cityId'=>12],
            ['id'=>212, 'region'=>'Sousse Jaouhara', 'cityId'=>12],
            ['id'=>213, 'region'=>'Sousse Médina', 'cityId'=>12],
            ['id'=>214, 'region'=>'Sousse Riadh', 'cityId'=>12],
            ['id'=>215, 'region'=>'Sousse Sidi Abdelhamid', 'cityId'=>12],
            ['id'=>216, 'region'=>'Zaouiet – Ksibat Thrayett', 'cityId'=>12],
            ['id'=>217, 'region'=>'Bir Lahmar', 'cityId'=>21],
            ['id'=>218, 'region'=>'Dhehiba', 'cityId'=>21],
            ['id'=>219, 'region'=>'Ghomrassen', 'cityId'=>21],
            ['id'=>220, 'region'=>'Remada', 'cityId'=>21],
            ['id'=>221, 'region'=>'Smâr', 'cityId'=>21],
            ['id'=>222, 'region'=>'Tataouine Nord', 'cityId'=>21],
            ['id'=>223, 'region'=>'Tataouine Sud', 'cityId'=>21],
            ['id'=>224, 'region'=>'Degache', 'cityId'=>23],
            ['id'=>225, 'region'=>'Hazoua', 'cityId'=>23],
            ['id'=>226, 'region'=>'Nefta', 'cityId'=>23],
            ['id'=>227, 'region'=>'Tameghza', 'cityId'=>23],
            ['id'=>228, 'region'=>'Tozeur', 'cityId'=>23],
            ['id'=>229, 'region'=>'Bab El Bhar', 'cityId'=>1],
            ['id'=>230, 'region'=>'Bab Souika', 'cityId'=>1],
            ['id'=>231, 'region'=>'Carthage', 'cityId'=>1],
            ['id'=>232, 'region'=>'Cité El Khadra', 'cityId'=>1],
            ['id'=>233, 'region'=>'Djebel Jelloud', 'cityId'=>1],
            ['id'=>234, 'region'=>'El Kabaria', 'cityId'=>1],
            ['id'=>235, 'region'=>'El Menzah', 'cityId'=>1],
            ['id'=>236, 'region'=>'El Omrane', 'cityId'=>1],
            ['id'=>237, 'region'=>'El Omrane Supérieur', 'cityId'=>1],
            ['id'=>238, 'region'=>'El Ouardia', 'cityId'=>1],
            ['id'=>239, 'region'=>'Ettahrir', 'cityId'=>1],
            ['id'=>240, 'region'=>'Ezzouhour', 'cityId'=>1],
            ['id'=>241, 'region'=>'Hraïria', 'cityId'=>1],
            ['id'=>242, 'region'=>'La Goulette', 'cityId'=>1],
            ['id'=>243, 'region'=>'La Marsa', 'cityId'=>1],
            ['id'=>244, 'region'=>'Le Bardo', 'cityId'=>1],
            ['id'=>245, 'region'=>'Le Kram', 'cityId'=>1],
            ['id'=>246, 'region'=>'Médina', 'cityId'=>1],
            ['id'=>247, 'region'=>'Sidi El Bechir', 'cityId'=>1],
            ['id'=>248, 'region'=>'Sidi Hassine', 'cityId'=>1],
            ['id'=>249, 'region'=>'Sijoumi', 'cityId'=>1],
            ['id'=>250, 'region'=>'Bir Mchergua', 'cityId'=>6],
            ['id'=>251, 'region'=>'El Fahs', 'cityId'=>6],
            ['id'=>252, 'region'=>'Nadhour', 'cityId'=>6],
            ['id'=>253, 'region'=>'Saouaf', 'cityId'=>6],
            ['id'=>254, 'region'=>'Zaghouan', 'cityId'=>6],
            ['id'=>255, 'region'=>'Zriba', 'cityId'=>6],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('region');
    }
};
